services:
  dockge:
    image: embycrack:latest
    container_name: mb3admin.com
    restart: always
    ports:
      - 443:443
    networks:
      - ipv4_ipv6
networks:
  ipv4_ipv6:
    external: true